### ISSUE TITLE
GUI Needs

### ISSUE THREAD

**Issue by Gondee** [Gondee/pMIR#17]
-Android Chart to display a graph like in the second picture:
mljs/pca#5
For this demonstration, we at most we will need to use three unique colored points:
A- for training data that is not close to the new sample.
B- for the training data point closest to the new sample.
C- for the new sample.
-User opens app and is queried for load or new model.
-If load, do file system stuff to look up model.
-If new, ask to do scans using standard procedures.
~~-After scan, ask for file name, concentrations, and concentration names~~
-User can hit next sample, and done (save) which asks for a file name.
-We assume PCA since that is what we present next time.
-Query new scan, after scanning display the android chart with words above it stating what it thinks it is.

**Comment by Gondee** [comment]
Doing Post Scan Page now.

**Comment by Gondee** [comment]
@IannothSlurgh Angular Chart doesn't have a scatter plot. Is that the Ideal way to show the PCA data?

**Comment by IannothSlurgh** [comment]
Unfortunately yes.

**Comment by IannothSlurgh** [comment]
SInce we are only having one training set:
-toggle training to on, and pressing done in postscan should call database.importDataFile passing csv data to it as well as the user input.

-Toggling training off should call chemo.train with the file names of all currently stored files.

-While toggled off, completing scan information should run chemo.infer and plot the points stored in chemoPCACompressed (currently not accessible, make accessible) as well as the point in measured (the recent scan's location on graph, also currently not accessible).

-In order to keep track of the files currently available for the training data, you can use the database.listEntries(false) which will return an array of the filenames of the scan data. Keeping track of filenames is important because you will have to keep passing them to chemo.train() every time user unchecks training.

So what does this mean? The only portion of visible GUI left before demonstration is the chart with all its points (and the principle components as vectors if that can be handled). The rest is solely writing directives that do the right things (it appears).

**Comment by IannothSlurgh** [comment]
We are done.
